name: CI-CD

on: 
  push: 
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v5.0.0

      - name: Autenticação no Docker Hub
      - uses: docker/login-action@v3.5.0
      - with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v6.18.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            caiohenrique/live-kube-news:v1
            caiohenrique/live-kube-news:latest
            
